### ISSUE TITLE
Script no longer works when before it used to work

### ISSUE THREAD

**Issue by ienzo** [MiniGlome/Archive.org-Downloader#44] opened 2022-07-20 10:29 UTC
Initially I used an older version, but it also does not work on the latest version. 

The command I inputted was (with email and password redacted):

```
python3 archive-org-downloader.py -e email@email.com -p password -u https://archive.org/details/anarchistvoiceso0000avri
```

It gave the following output before quitting without generating any files.

```
1 Book(s) to download
[+] Successful login
========================================
Current book: https://archive.org/details/anarchistvoiceso0000avri
[+] Successful loan
Traceback (most recent call last):
  File "archive-org-downloader.py", line 209, in <module>
    title, links = get_book_infos(session, url)
  File "archive-org-downloader.py", line 22, in get_book_infos
    response = session.get(infos_url)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 546, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 519, in request
    prep = self.prepare_request(req)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 452, in prepare_request
    p.prepare(
  File "/usr/lib/python3/dist-packages/requests/models.py", line 313, in prepare
    self.prepare_url(url, params)
  File "/usr/lib/python3/dist-packages/requests/models.py", line 390, in prepare_url
    raise InvalidURL("Invalid URL %r: No host supplied" % url)
requests.exceptions.InvalidURL: Invalid URL 'https:TYPE html>\n<html lang="en">\n<!-- __ _ _ _ __| |_ (_)__ _____\n    / _` | \'_/ _| \' \\| |\\ V / -_)\n    \\__,_|_| \\__|_||_|_| \\_/\\___| -->\n  <head data-release=8a2d548c>\n   .... 
```

I redacted the rest after "...." because it seems to be all html and it doesn't fit into the comment.

**Comment by MiniGlome** [comment] 2022-07-22 17:33
Duplicate of issue #42

**Closed by MiniGlome** 2022-07-22 17:33 UTC
